spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/notification
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8080/h2-console

  sql.init.mode: always
  data.web.pageable.max-page-size: 50

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  sql:
    init:
      data-locations: